name: Publish to Packagist
on:
  release:
    types: [created]
jobs:
  build-n-publish:
    name: Build and publish Composer distributions ğŸ“¦ to Packagist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish distribution ğŸ“¦ to Packagist
        uses: mnavarrocarter/packagist-update@release/v1
        with:
          username: "eversend"
          api_token: ${{ secrets.PACKAGIST_TOKEN }}